def generate_generalized_abbreviation(word):
    '''
    Given a word, write a function to generate all of its unique generalized abbreviations.
    Generalized abbreviation of a word can be generated by replacing each substring
    of the word by the count of characters in the substring.
    Take the example of “ab” which has four substrings: “”, “a”, “b”, and “ab”.
    After replacing these substrings in the actual word by the count of characters
    we get all the generalized abbreviations: “ab”, “1b”, “a1”, and “2”.
    '''
    result = []

    return result


def main():
    print("Generalized abbreviation are: " +
        str(generate_generalized_abbreviation("BAT")))
    print("Generalized abbreviation are: " +
        str(generate_generalized_abbreviation("code")))


main()
